// AUTO-GENERATED by `cargo xtask gen-manifest` - DO NOT EDIT

import type { Highlight } from "./types.js"; 

/** Version of plugin packages (all @arborium/* packages share this version) */
export const pluginVersion = "<%= version %>";

/** All available languages */
export const availableLanguages: string[] = [
<% for lang in languages { %>  "<%= lang %>",
<% } %>];

/** All possible highlights and their short tags */
export const highlights: Highlight[] = [
<% for hl in highlights { %>  {
    name: "<%= hl.name %>",
    tag: "<%= hl.def.tag %>",<% if let Some(parent) = &hl.def.parent { %>
    parentTag: "<%= parent %>",<% } %>
  },
<% } %>];
